package cms

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestFuncName(t *testing.T) {
	tests := []struct {
		filename string
		want     string
	}{
		{"index.templ", "IndexPage"},
		{"about.templ", "AboutPage"},
		{"entry.templ", "EntryPage"},
		{"contact-us.templ", "ContactUsPage"},
		{"my-cool-page.templ", "MyCoolPagePage"},
		{"getting-started.templ", "GettingStartedPage"},
	}
	for _, tt := range tests {
		got := funcName(tt.filename)
		if got != tt.want {
			t.Errorf("funcName(%q) = %q, want %q", tt.filename, got, tt.want)
		}
	}
}

func TestGenerateRoutes_BasicStructure(t *testing.T) {
	dir := t.TempDir()

	// Set up pages directory structure.
	pagesDir := filepath.Join(dir, "pages")
	writeTemplFile(t, pagesDir, "layout.templ")
	writeTemplFile(t, pagesDir, "index.templ")
	writeTemplFile(t, pagesDir, "about.templ")
	writeTemplFile(t, pagesDir, "blog/index.templ")
	writeTemplFile(t, pagesDir, "blog/entry.templ")

	code, err := GenerateRoutes(GenerateConfig{
		PagesDir:   pagesDir,
		ModulePath: "myapp",
		Package:    "main",
	})
	if err != nil {
		t.Fatal(err)
	}

	// Should have the generated header.
	if !strings.Contains(code, "Code generated by go-cms") {
		t.Error("missing generated header")
	}

	// Should import the pages package.
	if !strings.Contains(code, `"myapp/pages"`) {
		t.Errorf("missing pages import:\n%s", code)
	}

	// Should import the blog sub-package.
	if !strings.Contains(code, `"myapp/pages/blog"`) {
		t.Errorf("missing blog import:\n%s", code)
	}

	// Should register root layout.
	if !strings.Contains(code, `app.Layout("/", "root", pages.RootLayout)`) {
		t.Errorf("missing root layout registration:\n%s", code)
	}

	// Should register pages.
	if !strings.Contains(code, `app.Page("/", pages.IndexPage)`) {
		t.Errorf("missing / registration:\n%s", code)
	}
	if !strings.Contains(code, `app.Page("/about", pages.AboutPage)`) {
		t.Errorf("missing /about registration:\n%s", code)
	}

	// Should register collection.
	if !strings.Contains(code, `app.Collection("/blog", "Blog", blog.IndexPage, blog.EntryPage)`) {
		t.Errorf("missing blog collection registration:\n%s", code)
	}
}

func TestGenerateRoutes_NoBlog(t *testing.T) {
	dir := t.TempDir()

	pagesDir := filepath.Join(dir, "pages")
	writeTemplFile(t, pagesDir, "index.templ")
	writeTemplFile(t, pagesDir, "about.templ")
	writeTemplFile(t, pagesDir, "contact-us.templ")

	code, err := GenerateRoutes(GenerateConfig{
		PagesDir:   pagesDir,
		ModulePath: "myapp",
		Package:    "main",
	})
	if err != nil {
		t.Fatal(err)
	}

	if !strings.Contains(code, `app.Page("/", pages.IndexPage)`) {
		t.Errorf("missing / registration:\n%s", code)
	}
	if !strings.Contains(code, `app.Page("/about", pages.AboutPage)`) {
		t.Errorf("missing /about registration:\n%s", code)
	}
	if !strings.Contains(code, `app.Page("/contact-us", pages.ContactUsPage)`) {
		t.Errorf("missing /contact-us registration:\n%s", code)
	}

	// Should NOT have Collection calls.
	if strings.Contains(code, "Collection") {
		t.Errorf("unexpected Collection call:\n%s", code)
	}

	// Should NOT import blog.
	if strings.Contains(code, "blog") {
		t.Errorf("unexpected blog import:\n%s", code)
	}
}

func TestGenerateRoutes_MultipleCollections(t *testing.T) {
	dir := t.TempDir()

	pagesDir := filepath.Join(dir, "pages")
	writeTemplFile(t, pagesDir, "index.templ")
	writeTemplFile(t, pagesDir, "blog/index.templ")
	writeTemplFile(t, pagesDir, "blog/entry.templ")
	writeTemplFile(t, pagesDir, "products/index.templ")
	writeTemplFile(t, pagesDir, "products/entry.templ")

	code, err := GenerateRoutes(GenerateConfig{
		PagesDir:   pagesDir,
		ModulePath: "myapp",
		Package:    "main",
	})
	if err != nil {
		t.Fatal(err)
	}

	if !strings.Contains(code, `app.Collection("/blog", "Blog", blog.IndexPage, blog.EntryPage)`) {
		t.Errorf("missing blog collection:\n%s", code)
	}
	if !strings.Contains(code, `app.Collection("/products", "Products", products.IndexPage, products.EntryPage)`) {
		t.Errorf("missing products collection:\n%s", code)
	}
}

func TestGenerateRoutes_NestedLayouts(t *testing.T) {
	dir := t.TempDir()

	pagesDir := filepath.Join(dir, "pages")
	writeTemplFile(t, pagesDir, "layout.templ")
	writeTemplFile(t, pagesDir, "index.templ")
	writeTemplFile(t, pagesDir, "docs/layout.templ")
	writeTemplFile(t, pagesDir, "docs/index.templ")
	writeTemplFile(t, pagesDir, "docs/getting-started.templ")

	code, err := GenerateRoutes(GenerateConfig{
		PagesDir:   pagesDir,
		ModulePath: "myapp",
		Package:    "main",
	})
	if err != nil {
		t.Fatal(err)
	}

	// Should register both layouts, root first.
	if !strings.Contains(code, `app.Layout("/", "root", pages.RootLayout)`) {
		t.Errorf("missing root layout:\n%s", code)
	}
	if !strings.Contains(code, `app.Layout("/docs", "docs", docs.RootLayout)`) {
		t.Errorf("missing docs layout:\n%s", code)
	}

	// Should import docs sub-package.
	if !strings.Contains(code, `"myapp/pages/docs"`) {
		t.Errorf("missing docs import:\n%s", code)
	}

	// Should register pages.
	if !strings.Contains(code, `app.Page("/docs", docs.IndexPage)`) {
		t.Errorf("missing /docs page:\n%s", code)
	}
	if !strings.Contains(code, `app.Page("/docs/getting-started", docs.GettingStartedPage)`) {
		t.Errorf("missing /docs/getting-started page:\n%s", code)
	}
}

func TestGenerateRoutes_NoLayout(t *testing.T) {
	dir := t.TempDir()

	pagesDir := filepath.Join(dir, "pages")
	writeTemplFile(t, pagesDir, "index.templ")
	writeTemplFile(t, pagesDir, "about.templ")

	code, err := GenerateRoutes(GenerateConfig{
		PagesDir:   pagesDir,
		ModulePath: "myapp",
		Package:    "main",
	})
	if err != nil {
		t.Fatal(err)
	}

	// Should NOT have Layout calls.
	if strings.Contains(code, "Layout") {
		t.Errorf("unexpected Layout call:\n%s", code)
	}
}

func TestGenerateRoutes_WritesFile(t *testing.T) {
	dir := t.TempDir()

	pagesDir := filepath.Join(dir, "pages")
	writeTemplFile(t, pagesDir, "index.templ")

	outFile := filepath.Join(dir, "routes_gen.go")

	err := WriteGeneratedRoutes(GenerateConfig{
		PagesDir:   pagesDir,
		ModulePath: "myapp",
		Package:    "main",
	}, outFile)
	if err != nil {
		t.Fatal(err)
	}

	content, err := os.ReadFile(outFile)
	if err != nil {
		t.Fatal(err)
	}

	if !strings.Contains(string(content), "RegisterRoutes") {
		t.Errorf("generated file missing RegisterRoutes:\n%s", string(content))
	}
}
