// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"encoding/json"
	cms "go.a-line.be/cms"
	"strings"
)

// jsonLDScript wraps a JSON string in a <script type="application/ld+json"> tag.
func jsonLDScript(data string) string {
	return `<script type="application/ld+json">` + data + `</script>`
}

// SchemaWebSite renders a WebSite JSON-LD schema.
func SchemaWebSite(p cms.PageData) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		if p.SiteURL() != "" {
			templ_7745c5c3_Err = templ.Raw(jsonLDScript(buildWebSiteSchema(p))).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		return nil
	})
}

// SchemaLocalBusiness renders a LocalBusiness JSON-LD schema.
func SchemaLocalBusiness(p cms.PageData) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templ.Raw(jsonLDScript(buildLocalBusinessSchema(p))).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// SchemaPerson renders a Person JSON-LD schema for the business owner.
func SchemaPerson(p cms.PageData) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var3 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var3 == nil {
			templ_7745c5c3_Var3 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templ.Raw(jsonLDScript(buildPersonSchema(p))).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// SchemaServices renders Service JSON-LD schemas.
func SchemaServices(p cms.PageData) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var4 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var4 == nil {
			templ_7745c5c3_Var4 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templ.Raw(jsonLDScript(buildServicesSchema(p))).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// SchemaBreadcrumb renders a BreadcrumbList JSON-LD schema.
func SchemaBreadcrumb(p cms.PageData) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var5 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var5 == nil {
			templ_7745c5c3_Var5 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		if p.SiteURL() != "" {
			templ_7745c5c3_Err = templ.Raw(jsonLDScript(buildBreadcrumbSchema(p))).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		return nil
	})
}

// --- JSON builders ---

func buildWebSiteSchema(p cms.PageData) string {
	schema := map[string]any{
		"@context": "https://schema.org",
		"@type":    "WebSite",
		"url":      p.SiteURL() + "/",
	}
	if p.SiteName() != "" {
		schema["name"] = p.SiteName()
	}
	b, _ := json.Marshal(schema)
	return string(b)
}

func buildLocalBusinessSchema(p cms.PageData) string {
	c := p.SEOConfig()
	schema := map[string]any{
		"@context": "https://schema.org",
		"@type":    c.BusinessType,
		"name":     c.BusinessName,
	}
	if p.SiteURL() != "" {
		schema["url"] = p.SiteURL() + "/"
	}
	if c.Phone != "" {
		schema["telephone"] = c.Phone
	}
	if c.Email != "" {
		schema["email"] = c.Email
	}
	if c.PriceRange != "" {
		schema["priceRange"] = c.PriceRange
	}
	if c.FoundingDate != "" {
		schema["foundingDate"] = c.FoundingDate
	}
	if c.VatID != "" {
		schema["vatID"] = c.VatID
	}

	// Address
	if c.StreetAddress != "" || c.AddressLocality != "" {
		addr := map[string]any{
			"@type": "PostalAddress",
		}
		if c.StreetAddress != "" {
			addr["streetAddress"] = c.StreetAddress
		}
		if c.AddressLocality != "" {
			addr["addressLocality"] = c.AddressLocality
		}
		if c.AddressRegion != "" {
			addr["addressRegion"] = c.AddressRegion
		}
		if c.PostalCode != "" {
			addr["postalCode"] = c.PostalCode
		}
		if c.AddressCountry != "" {
			addr["addressCountry"] = c.AddressCountry
		}
		schema["address"] = addr
	}

	// Geo coordinates
	if c.GeoLat != nil && c.GeoLng != nil {
		schema["geo"] = map[string]any{
			"@type":     "GeoCoordinates",
			"latitude":  *c.GeoLat,
			"longitude": *c.GeoLng,
		}
	}

	// Service areas
	if len(c.ServiceAreas) > 0 {
		areas := make([]map[string]any, len(c.ServiceAreas))
		for i, area := range c.ServiceAreas {
			areas[i] = map[string]any{
				"@type": "GeoCircle",
				"geoMidpoint": map[string]any{
					"@type": "GeoCoordinates",
					"name":  area,
				},
			}
		}
		schema["areaServed"] = areas
	}

	// Opening hours
	if len(c.OpeningHours) > 0 {
		var specs []map[string]any
		for _, oh := range c.OpeningHours {
			if oh.Days == "" {
				continue
			}
			spec := map[string]any{
				"@type":     "OpeningHoursSpecification",
				"dayOfWeek": strings.Split(oh.Days, ","),
			}
			if oh.Opens != "" {
				spec["opens"] = oh.Opens
			}
			if oh.Closes != "" {
				spec["closes"] = oh.Closes
			}
			specs = append(specs, spec)
		}
		if len(specs) > 0 {
			schema["openingHoursSpecification"] = specs
		}
	}

	// Social profiles
	if len(c.SocialProfiles) > 0 {
		schema["sameAs"] = c.SocialProfiles
	}

	// Default image
	if c.DefaultOGImageURL != "" {
		schema["image"] = c.DefaultOGImageURL
	}

	b, _ := json.Marshal(schema)
	return string(b)
}

func buildPersonSchema(p cms.PageData) string {
	c := p.SEOConfig()
	schema := map[string]any{
		"@context": "https://schema.org",
		"@type":    "Person",
		"name":     c.OwnerName,
	}
	if c.OwnerJobTitle != "" {
		schema["jobTitle"] = c.OwnerJobTitle
	}
	if c.OwnerDescription != "" {
		schema["description"] = c.OwnerDescription
	}
	if c.OwnerImageURL != "" {
		schema["image"] = c.OwnerImageURL
	}
	if p.SiteURL() != "" {
		schema["url"] = p.SiteURL() + "/"
	}
	if len(c.OwnerSameAs) > 0 {
		schema["sameAs"] = c.OwnerSameAs
	}
	// Link to the business
	if c.BusinessName != "" {
		schema["worksFor"] = map[string]any{
			"@type": c.BusinessType,
			"name":  c.BusinessName,
		}
	}
	b, _ := json.Marshal(schema)
	return string(b)
}

func buildServicesSchema(p cms.PageData) string {
	c := p.SEOConfig()
	var services []map[string]any
	for _, svc := range c.Services {
		if svc.Name == "" {
			continue
		}
		s := map[string]any{
			"@type": "Service",
			"name":  svc.Name,
		}
		if svc.Description != "" {
			s["description"] = svc.Description
		}
		if c.BusinessName != "" {
			s["provider"] = map[string]any{
				"@type": c.BusinessType,
				"name":  c.BusinessName,
			}
		}
		if len(c.ServiceAreas) > 0 {
			s["areaServed"] = c.ServiceAreas
		}
		services = append(services, s)
	}
	wrapper := map[string]any{
		"@context": "https://schema.org",
		"@graph":   services,
	}
	b, _ := json.Marshal(wrapper)
	return string(b)
}

func buildBreadcrumbSchema(p cms.PageData) string {
	siteURL := p.SiteURL()
	path := p.ContentPath()

	items := []map[string]any{
		{
			"@type":    "ListItem",
			"position": 1,
			"name":     "Home",
			"item":     siteURL + "/",
		},
	}

	if path != "/" {
		parts := strings.Split(strings.Trim(path, "/"), "/")
		for i, part := range parts {
			// Build URL up to this segment
			segPath := "/" + strings.Join(parts[:i+1], "/") + "/"
			items = append(items, map[string]any{
				"@type":    "ListItem",
				"position": i + 2,
				"name":     strings.Title(strings.ReplaceAll(part, "-", " ")),
				"item":     siteURL + segPath,
			})
		}
	}

	schema := map[string]any{
		"@context":        "https://schema.org",
		"@type":           "BreadcrumbList",
		"itemListElement": items,
	}
	b, _ := json.Marshal(schema)
	return string(b)
}

var _ = templruntime.GeneratedTemplate
